### ISSUE TITLE
./scripts/prepareMaster.sh - NFS share size for registry is hardcoded

### ISSUE THREAD

**Issue by alexbez** [mglantz/ocp36-azure-simple#13]
No matter how big the persistent storage volume, prepareMaster.sh script always allocates 20 Gib for /dev/docker-vg/lv_nfs volume by doing the following:

lvextend -L 20G /dev/docker-vg/lv_nfs 
xfs_growfs /dev/docker-vg/lv_nfs

Better have it a a separate parameter in azuredeploy.parameters.json or to calculate the size based on the free storage size available.  20 GiB is not always enough.

**Comment by mglantz** [comment]
Agreed, we should instead take what's free.

**Comment by mglantz** [comment]
Fixed in https://github.com/mglantz/ocp36-azure-simple/commit/0bd3c6373a84d7a986ed1d7b97d60d6b8afa694b
