### ISSUE TITLE
After HA installation in Azure the Registry is misconfigured

### ISSUE THREAD

**Issue by alexbez** [mglantz/ocp36-azure-simple#6]
All builds fail with the error message:

error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp: lookup docker-registry.default.svc on 192.168.2.9:53: no such host

'oc adm diagnostics' reports that:
...
[Note] Running diagnostic: ClusterRegistry
       Description: Check that there is a working Docker registry

ERROR: [DClu1019 from diagnostic ClusterRegistry@openshift/origin/pkg/diagnostics/cluster/registry.go:343]
       Diagnostics created a test ImageStream and compared the registry IP
       it received to the registry IP available via the docker-registry service.

       docker-registry      : 172.30.168.12:5000
       ImageStream registry : docker-registry.default.svc:5000

       They do not match, which probably means that an administrator re-created
       the docker-registry service but the master has cached the old service
       IP address. Builds or deployments that use ImageStreams with the wrong
       docker-registry IP will fail under this condition.

       To resolve this issue, restarting the master (to clear the cache) should
       be sufficient. Existing ImageStreams may need to be re-created.

Restarting masters by the following command did not solve the problem:
ocpmaster# systemctl restart atomic-openshift-master-api atomic-openshift-master-controllers

**Comment by mglantz** [comment]
Thanks for catching this problem. I did bump into it as well and have commited a fix here: https://github.com/mglantz/ocp36-azure-simple/commit/4dcc554da94a194ae6cbc9e7cd3c8e2029531e2c

What happens if you reboot the masters servers? You can do this without issues as long as you are not actively deploying things. They are quite robust.

**Comment by alexbez** [comment]
I have rebooted all masters and restarted docker registry services as well. Now the image stream picks the correct registry URL, however push to the registry fails with "HTTPS server sent HTTP reply" error message - but this needs to be reported as a separate issue, I guess? Adding 172.30.0.0/16 to list of insecure registries on all nodes and restarting docker services did not fix the issue.

**Comment by mglantz** [comment]
Fix verified, not sure why it's didn't work on an existing cluster though. Closing this issue.
