### ISSUE TITLE
deply.sh: KeyVaultName is a constant

### ISSUE THREAD

**Issue by alexbez** [mglantz/ocp36-azure-simple#7]
azure keyvault create -u ${GROUP}KeyVaultName -g $GROUP -l $LOCATION
azure keyvault secret set -u ${GROUP}KeyVaultName -s ${GROUP}Secret --file ~/.ssh/id_rsa
azure keyvault set-policy -u ${GROUP}KeyVaultName --enabled-for-template-deployment true

KeyVaultName is a literal, not a parameter, so all deployments use the same name for the key vault.

**Comment by mglantz** [comment]
Thanks for the feedback. It works this way out of simplification purposes. To not have to set specific variables for KeyVault and Secret. As deployments (at least this would be recommended) are in separate resource groups, this is not an issue. Or?

**Comment by alexbez** [comment]
Indeed, deployment of different clusters shall happen in different resource groups. However it is a recommended practice to have a separate resource group just for the key vaults - this way they can be shared and reused between multiple cluster installations to avoid data duplication. Also Azure does not really have namespaces, so choosing your own name for the key vault can resolve name conflicts.

So I suggest to have a separate parameters for the key vault's RG and for key vault name, but to have set default values for them.

**Comment by mglantz** [comment]
Fixed in https://github.com/mglantz/ocp36-azure-simple/commit/ac5aa1249448dee027829ab68b7c4d3ad0a384bc
